// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb || defaultTargetPlatform == TargetPlatform.windows) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUQgAcIwSLqXJ1eFKIg8jBuRUFktySOvs',
    appId: '1:341194391447:web:bd473dd4586963f7b08ed2',
    messagingSenderId: '341194391447',
    projectId: 'flutter1-ad4a1',
    authDomain: 'flutter1-ad4a1.firebaseapp.com',
    storageBucket: 'flutter1-ad4a1.appspot.com',
    measurementId: 'G-92HDRNJT3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUZk1xtHll3L_Ectq99A7oC9QfAPE-s58',
    appId: '1:341194391447:android:c2bcc24ad6fe5d07b08ed2',
    messagingSenderId: '341194391447',
    projectId: 'flutter1-ad4a1',
    storageBucket: 'flutter1-ad4a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe54U8o_ZVL8iEOaRYzOEeTlP9Rhc3mXc',
    appId: '1:341194391447:ios:b4b0d400d49f957ab08ed2',
    messagingSenderId: '341194391447',
    projectId: 'flutter1-ad4a1',
    storageBucket: 'flutter1-ad4a1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe54U8o_ZVL8iEOaRYzOEeTlP9Rhc3mXc',
    appId: '1:341194391447:ios:f9aef2ea92b8f6e3b08ed2',
    messagingSenderId: '341194391447',
    projectId: 'flutter1-ad4a1',
    storageBucket: 'flutter1-ad4a1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
